import Modal from "../components/modal";
import Button from "../components/button";
import { useState } from "react";


function ModalPage() {

    const [showModal, setShowModal] = useState(false);

    const handleClick = () => {
        setShowModal(true);
    }

    const handleClose = () => {
        setShowModal(false);
    }

    const actionBar = <div>
                        <Button onClick={handleClose} primary> I accept</Button>
                    </div>;
    const modal = <Modal onClose={handleClose} actionBar={actionBar}>
                    <p>Here is an agreement</p>
                </Modal>

    return (<div>
        <Button primary onClick={handleClick}>Open Modal</Button>
        {showModal && modal }
        
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a convallis nibh. Sed facilisis pretium nisl nec fermentum. Pellentesque lacinia porta sodales. Nullam rutrum efficitur nunc et lobortis. Aenean felis ex, porta eu tortor at, porta vestibulum eros. Morbi massa est, rhoncus nec eros ac, rutrum consectetur ex. Donec eu vestibulum lorem. Integer efficitur orci tellus, at ornare sem vestibulum a.

Duis a felis sodales, feugiat est ut, tincidunt metus. Integer vitae lorem non erat luctus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi mi orci, varius ac molestie quis, imperdiet eu arcu. Nunc pellentesque nunc vel erat malesuada aliquam. Aliquam tincidunt elementum metus quis tristique. Morbi mauris augue, molestie non nulla pulvinar, maximus vulputate lectus.

Mauris sit amet metus ut lacus viverra varius porta eu ex. Aliquam a mauris consequat, condimentum arcu eget, hendrerit lectus. Proin eu euismod mauris. Donec quis nibh nec lorem tincidunt eleifend ut vitae felis. Integer auctor at justo blandit fringilla. Quisque vitae rhoncus nibh. Sed rutrum nunc mi, eget convallis libero tempor eget. In sodales magna at libero aliquam, ac facilisis elit varius. Nullam eleifend ac sapien ut semper. Donec non suscipit ligula, viverra aliquet purus. Vestibulum vulputate augue ac justo posuere, nec auctor turpis convallis. Aliquam convallis nibh sit amet purus luctus, id pretium dui porttitor. Fusce lectus ipsum, pellentesque eget elementum eget, placerat a risus. Nunc auctor libero ac dolor tincidunt, ut condimentum nisl accumsan. Duis lacinia imperdiet maximus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sed mauris leo. In semper eu turpis sed tincidunt. Fusce velit odio, consectetur eget nibh vitae, tincidunt lacinia nisl. Curabitur euismod nisi vitae turpis gravida, vitae ultrices lorem lobortis. Donec malesuada, diam nec iaculis sodales, lacus augue porttitor massa, vitae tempor diam justo sed purus. In in felis ligula. Proin cursus dui eros, ut ullamcorper nibh rhoncus sed. Sed pulvinar suscipit rhoncus. Proin eget ipsum quam. Nam at massa dignissim lacus dignissim mattis sit amet id arcu. Vivamus tempor metus a risus finibus aliquet. Aenean nec venenatis tellus. Quisque fringilla dui a urna porta, id rutrum sapien sagittis.

Morbi nec euismod tellus. Phasellus faucibus quam ex, accumsan molestie eros malesuada et. Phasellus velit nibh, volutpat et elementum in, consectetur placerat nibh. Duis a dictum eros, ac mollis odio. Praesent non nibh a dui ultrices commodo. Nullam nec ante efficitur, euismod libero sed, mollis arcu. In hac habitasse platea dictumst. Nam mattis auctor neque vitae bibendum. In lorem felis, suscipit ut arcu non, ultrices maximus orci. Aliquam tempus enim a ipsum posuere consequat.
        </p>

        
        </div>);
}

export default ModalPage;